spring:
  jmx:
    default-domain: ${spring.application.name}
  security:
    oauth2:
      client:
        oauth2:
          client:
            registration:
              saasy:
                client-id: 123456789
                client-secret: 2b|!2b
                client-name: saasy
                scope: user_info
                provider: sassy
                redirect-uri-template: http://localhost:8080/login/oauth2/code/
                client-authentication-method: basic
                authorization-grant-type: authorization_code
            provider:
              saasy:
                token-uri: http://localhost:8443/auth/oauth/token
                authorization-uri: http://localhost:8443/auth/oauth/authorize
                user-info-uri: http://localhost:8443/auth/user/me
                user-name-attribute: name
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8443/auth/oauth/token
