spring:
  jmx:
    default-domain: ${spring.application.name}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-demo-app
            client-secret: ${spring.application.client-secret}
            scope: openid
        provider:
          keycloak:
            jwk-set-uri: https://keycloak.bluntsoftware.com/auth/realms/dev-spring/protocol/openid-connect/certs
            issuer-uri: https://keycloak.bluntsoftware.com/auth/realms/dev-spring
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak.bluntsoftware.com/auth/realms/dev-spring/protocol/openid-connect/certs
