spring:
  jmx:
    default-domain: ${spring.application.name}
  security:
    oauth2:
      client:
        registration:
          oauth2:
            client-id: spring-demo-app
            client-secret: '{cipher}AQBv9eqcJCpQkGOqOwdmbho0Dd8mXtL4ektz2zNKrQaqD0zI5akl6lRJzwSsuPk4dvqXDXMi6x96cMF+5ZJx/X4euNVAVu8HtEMNao/1SLa2jdlxZcn324GvHMDoVZ2iWT5psWQzrb6tALnKuvxQoc+vYAq/x1PXYmsEz/VITvF/zob8UwL+UTuwepmYSsbEbEApzw5h3t0VqkgkGpHCyeUQV1iAOk0TvCZcuILjYENR6mzUMCbO8Qgt9RCK8PMmmbxyz1LYPausH39Bz5JROEXwuwwGd2GaeUopHaoMLf7UHilkvE7dUMrdL8NrummZ/xC1wd0eD6kpseJxPLTvjiWWjunh7kQcxb5iqe76DBvyOiTkXKFjZqB+tH6/gGwMnwGrmvZ2nDeV+zJ1Zux+kAW7B2wh9MfNTsixjuTDXvKiiA=='
            scope: openid
        provider:
          oauth2:
            issuer-uri: https://keycloak.bluntsoftware.com/auth/realms/dev-spring
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.bluntsoftware.com/auth/realms/dev-spring
