spring:
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-secret: '{cipher}AQAdsO4GlFLPxwV/FL7QE2XV8N46n1D30UM'
