app:
  name: ${spring.application.name}
server:
  address: localhost
  port: 8081
  use-forward-headers: true
  servlet:
    context-path: /
mongo:
  host: localhost
  port: 27017
management:
  endpoints:
    web:
      exposure:
        include: "*"
datadog:
  apiKey: "bbeb49faefe690665ac4d730b4da708b"
  enabled: true
  step: "PT10S"
spring:
  main:
    allow-bean-definition-overriding: true
