app:
  name: ludwig
spring:
  application:
    name: ludwig
server:
  address: localhost
  port: 8080
  use-forward-headers: true
  servlet:
    context-path: /
mongo:
  host: localhost
  port: 27017
management:
  endpoints:
    web:
      exposure:
        include: "*"
metrics:
  export:
    datadog:
      api-key: "bbeb49faefe690665ac4d730b4da708b"
      step: "30s"


